spring.application.name=web
server.port=3000
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:h2:file:./data/truno-crazzy;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
app.cors.allowed-origins=http://localhost:4200,https://verbose-broccoli-p5wx9jvjpqq3674g-3000.app.github.dev
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
